### ISSUE TITLE
Error while doing inference on binarized model.

### ISSUE THREAD

**Issue by nttstar** [hpi-xnor/BMXNet#40]
Hi authors, 
  I have trained a weight binarized model successfully and I can do inference on it before doing model binarizing. But while I convert the model to binarized format which has a much smaller size, an error occurs. Can you help me? The log shows below(in gpu mode):
```
Traceback (most recent call last):
  File "benchmark.py", line 55, in <module>
    model.forward(db, is_train=False)
  File "/root/codebase/BMXNet/python/mxnet/module/module.py", line 609, in forward
    self._exec_group.forward(data_batch, is_train)
  File "/root/codebase/BMXNet/python/mxnet/module/executor_group.py", line 416, in forward
    exec_.forward(is_train=is_train)
  File "/root/codebase/BMXNet/python/mxnet/executor.py", line 150, in forward
    ctypes.c_int(int(is_train))))
  File "/root/codebase/BMXNet/python/mxnet/base.py", line 146, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [21:14:12] /root/codebase/BMXNet/include/mxnet/./tensor_blob.h:217: Check failed: mshadow::DataType<DType>::kFlag == type_flag_ TBlob.get_with_shape: data type do not match specified type.Expected: 1 v.s. given 0
```

And in CPU mode:
```
Traceback (most recent call last):
  File "benchmark.py", line 55, in <module>
    model.forward(db, is_train=False)
  File "/root/codebase/BMXNet/python/mxnet/module/module.py", line 609, in forward
    self._exec_group.forward(data_batch, is_train)
  File "/root/codebase/BMXNet/python/mxnet/module/executor_group.py", line 416, in forward
    exec_.forward(is_train=is_train)
  File "/root/codebase/BMXNet/python/mxnet/executor.py", line 150, in forward
    ctypes.c_int(int(is_train))))
  File "/root/codebase/BMXNet/python/mxnet/base.py", line 146, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [21:15:01] /root/codebase/BMXNet/mshadow/mshadow/./././dot_engine-inl.h:763: Check failed: dst.size(0) == sleft[0] && dst.size(1) == sright[1] && sleft[1] == sright[0] dot-gemm: matrix shape mismatch
```

**Comment by nttstar** [comment]
```
enum TypeFlag {
  kFloat32 = 0,
  kFloat64 = 1,
  kFloat16 = 2,
  kUint8 = 3,
  kInt32 = 4,
  kInt8  = 5,
  kInt64 = 6,
};
```
It seems that I give the kFloat32 data type whie the model wants kFloat64, why?

**Comment by nttstar** [comment]
After use uint32 as binary word type, error msg of GPU mode become the same with the one under CPU mode, still can not work:
```
Traceback (most recent call last):
  File "benchmark.py", line 55, in <module>
    model.forward(db, is_train=False)
  File "/root/codebase/BMXNet/python/mxnet/module/module.py", line 609, in forward
    self._exec_group.forward(data_batch, is_train)
  File "/root/codebase/BMXNet/python/mxnet/module/executor_group.py", line 416, in forward
    exec_.forward(is_train=is_train)
  File "/root/codebase/BMXNet/python/mxnet/executor.py", line 150, in forward
    ctypes.c_int(int(is_train))))
  File "/root/codebase/BMXNet/python/mxnet/base.py", line 146, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [21:44:46] /root/codebase/BMXNet/mshadow/mshadow/./././dot_engine-inl.h:763: Check failed: dst.size(0) == sleft[0] && dst.size(1) == sright[1] && sleft[1] == sright[0] dot-gemm: matrix shape mismatch
```

**Comment by yanghaojin** [comment]
Hi,
the binarized model (after conversion) is only appropriate for CPU mode so that one can take advantages of XNOR and popcount CPU-instructions for inference. 
BMXNet supports using CUDA or cuDNN for training a binary model. but doesn't support binary operations in GPU-mode. So one should not run binarized model in GPU mode.

From your error log under CPU-mode, the issue was from "dot_engine-inl.h" which indicates that you are not going to call the xnor-based gemm kernel, but the standard dot engine, this is already wrong.

There are two points you might want to concern:
1. only run converted model in CPU-mode. After conversion check the model size, if you are using the **q**_conv or **q**_fc layer, the converted model size should be much smaller than its full precision version.
2. pls make sure that you are using the converted model and also the generated definition .json file (both start with "binarized_" ).  If not there will be a mismatch problem. The conversion process is actually the concatenation of weights in q_* layers, so the layer definition is changed accordingly.

**Comment by nttstar** [comment]
I found the problem:  QConvolution works well while QConvolution_v1 can not. 
By the way: is it possible to accelerate QConvolution on nvidia GPU?

**Comment by nttstar** [comment]
something more:
QConvolution_v1 can make my network converging(an hourglass architecture) while QConvolution can not. Is there any difference? 
But QConvolution_v1 is much slower than QConvolution, even slower than fp32 implementation.
(both with act_bit=1, weight_bit=1 setting)

**Comment by SemaMediaData** [comment]
Hi,
We have tested the XNOR+popcnt in CUDA on NVidia GPU at the beginning of
this project.
Unfortunately, without specific optimization, it is not able to outperform
cublas in terms of processing speed, and much slower than cuDNN.
We could try to optimize the cuda implementation but since it still remains
a software level optimization, will be hard to compare to cuDNN which is
directly optimized somehow on hardware.
I think it will definitely make sense to have a hardware level optimized
binary-gemm operator on GPU, but since this is not our strength, so will be
much better and more efficient to encourage some GPU experts to do this.

First of all, both QConv_V1 and QConv layers are based on the corresponding
MXNet layers.
According to QConv_v1, this is the old version of Conv layer in MXNet, the
MXNet authors re-implemented some important functions such as "im2col"
intended to get some speedup in the new version (in fact they use the
implementation from Caffe :-)).
But there also produces some strange effects, especially in training a
binary model. (We are working on those problems and will present in the new
tech report.)
After this upgrade, we also adapted it in BMXNet, and now Q_Convolution
layer can take advantages of cuDNN, but not the _V1 version.

If you have the problem with Q_Convolution layer during training, I would
suggest:
- use Nadam optimizer (adam works badly after this upgrade, sgd always
works but have to manually design your lr schedule)
- use lower initial learning rate e.g. 0.0001
- fine-tuning from your _V1 model. This is possible since the weights are
stored in the same manner.

hope this could help you a little bit.

Best
HJ


2018-03-28 9:38 GMT+02:00 Jia Guo <notifications@github.com>:

**Comment by nttstar** [comment]
@yanghaojin Sorry I deleted my reply as I found there're something wrong. I will report my experiments result in following days.

**Comment by nttstar** [comment]
Hi, @yanghaojin . Sorry to disturb you again.  Here’s some preliminary test results.

   1.  QConvolution is very hard to converge but QConvolution_v1 has no problem. (watching on the loss value from initial hundreds of iterations). I use RMSProp with a small learning rate.
   2.  QConvolution_v1 is very slow while doing inference compare to QConvolution on CPU.
   3.  I can not do inference(on CPU) while act_bit=32, the above error occur. I think this is a very critical bug.  
```
ACT_BIT=32
bit = 1
act1 = mx.sym.QActivation(data=bn1, act_bit=ACT_BIT, name=name + '_relu1', backward_only=True)
conv1 = mx.sym.QConvolution(data=act1, num_filter=int(num_filter*0.5), kernel=(1,1), stride=(1,1), pad=(0,0), no_bias=True, workspace=workspace, name=name + '_conv1', act_bit=ACT_BIT, weight_bit=bit)
```

No problem if ACT_BIT=1.
 
 Now I use QConvolution_v1 to train the model but modify its name to QConvolution via model-converter tool to do inference. It's working without any error but I haven't checked the results.

**Comment by yanghaojin** [comment]
hi, 
one tip for the inference, if you have a 64bits CPU, could also try to use uint64 as bits container which will give about 2x speedup on Conv_V1, and I would also suggest to enable OpenMP if available. So you don't need to retrain the model, just compile your BMXNet with "Binary_word_type=uint64", and convert the model again.

To the point 3, I think it is a "not implemented" issue, if the activation is full precision and perform dot product with binary weights, we then  need to convert the concatenated binary weights back to the float point version, this is not yet implemented, could be done in the future work.

**Comment by nttstar** [comment]
I see, so now the memory efficient weight-binarized model is not supported. Thanks for your reply!
I also confirmed that Nadam optimizer is better.

**Comment by yanghaojin** [comment]
the binarized (converted) model is only supported by using **act_bit = 1 and weight_bit=1**, this case, the allocated memory for weights is much smaller than the full precision one, and the forward pass in cpu-mode, the cpu instruction xnor and popcount will be applied for GEMM computation. Unfortunately, for your case **act_bit = 32 and weight_bit=1**, there is still no appropriate implementation.

**Comment by nttstar** [comment]
Yes I understood. Thank you again!

**Comment by nttstar** [comment]
Hi, what's your plan to release the next version of BMXNet?

**Comment by yanghaojin** [comment]
Hi, 
so there are still so many research questions in the BNN without a clear answer, e.g., the issue raised by Christopher Barber: why you use the binary weights for the update, the XNOR-net and DeReFaNet all use its full precision weights for the update. That way should be more reasonable. Well, from the first feeling probably yes, but we still need do more experiments to figure out it.  Should we use full precision or binary weights for the backpropagation? why is a certain choice better? The meaning of the scaling factor for BMXNet? The meaning of skip connections for BNN? 

Well, the next step or what we are doing is not only trying to achieve more accurate result using BNN but also trying to understand its behavior in training, e.g., get some insights from the visualization.

We plan to release more configuration possibilities that let you decide which one to use, e.g. using binary weight or full precision one for the update process. 
We will add the new features helping us to understand the BNN model, by which we are able to visualize the neurons learned from a certain layer and visualize the gradient intensity map from the backpropagation. We believe that getting more insights is especially necessary for BNN.
Moreover, we will release more trained model and probably also new network architecture for BNN.

**Comment by nttstar** [comment]
Thanks! Nvidia released tensorrt which now can support 8bit model conversion. Hope you can achieve a better performance/accuracy than it with lower bit.
