### ISSUE TITLE
forward speed problem

### ISSUE THREAD

**Issue by szc1523** [hpi-xnor/BMXNet#6]
i'm trying to benchmark resnet-18 and resnet-binary-18 using the benchmark_score.py in the binary-imagenet1k folder. 
the results are:
INFO:root:network: resnet-binary-18
INFO:root:device: gpu(0)
NFO:root:batch size  1, image/sec: 9.004076
INFO:root:batch size  8, image/sec: 12.565606
INFO:root:device: cpu(0)
INFO:root:batch size  1, image/sec: 0.661994
INFO:root:batch size  8, image/sec: 0.813232
INFO:root:network: resnet-18
INFO:root:device: gpu(0)
INFO:root:batch size  1, image/sec: 36.849257
INFO:root:batch size  8, image/sec: 48.341315
INFO:root:device: cpu(0)
INFO:root:batch size  1, image/sec: 0.552637
INFO:root:batch size  8, image/sec: 0.770370

it seems that binary resnet is a little faster than the vanilla resnet on CPU. However, in the figure 1 of the paper, binarized input and xnor_64_omp are 10 times faster than Cblas. 
is this the normal speed of binary resnet or i've made something wrong? and i found that when testing with CPU, only 1 thread is used, seems  openmp not working?

i'm using a ubuntu 14.04 machine, with openblas openmp installed.
CPU: Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz 
GPU: titanx maxwell

**Comment by yanghaojin** [comment]
Hi,
first of all, there is not efficiency improvement in GPU mode in our implementation. We don't apply xnor gemm for training, since we realize that CuDNN would be much more efficient for this job. Our solution is that we use CuDNN for training, the weights and input will be converted to  +1, -1 firstly, and after dot product we map the dot_output to xnor_dot_output according to Eq. 2 in our paper. This way, we can apply xnor gemm for the inference in CPU mode.  So the speed up achieved in this implementation is only in CPU mode.
The experimental result depicted in figure 1 is based on measurements performed within one convolution layer, where we fixed the parameters as follows: filter number=64, kernel size=5×5, batch size=200, and the matrix sizes M, N, K are 64, 12800, kernel_w×kernel_h×inputChannelSize, respectively. 
So in order to make a fair comparison to Cblas(Atlas), we only measure the processing time of gemm operation (one of our result also includes the processing time of input binarization).  But there is other time consuming processing steps such as "patchToCol" which takes a large proportion of the total processing time of a Conv layer. Therefore although we could achieve over 10 times acceleration in gemm computation, unfortunately for now it cannot achieve such a significant speed increase overall in a Conv layer or in a whole network.
On our testing machine: Ubuntu16.04/64-bit platform with Intel 2.50GHz×4 CPU with popcntin-struction (SSE4.2) I can achieve around 2x speed up by using binary ResNet-18-Cifar10 model compared to vanilla ResNet-18.  
Moreover, there are several factors may affected the inference efficiency: Compilation in Release not in Debug mode;  popcn-instruction (SSE4.2) support; OpenMp support; 64-bit (about 2x faster than 32-bit).
We will further investigate the speedup solution and continue this work.

**Comment by szc1523** [comment]
thanks for your great work and detailed reply，i'll try to reimplement your testing settings.

**Comment by ouceduxzk** [comment]
What is "patchToCol" exactly?

**Comment by yanghaojin** [comment]
pls refer to the function at https://github.com/hpi-xnor/BMXNet/blob/master/src/operator/convolution_v1-inl.h#L143
